theme: jekyll-theme-midnight
email: vicentemoscardo@gmail.com
title: "Puentes de Valencia"
description: "App de los puentes sobre el viejo cauce del r√≠o Turia en la ciudad de Valencia"
baseurl: ""
url: https://vmoscardo.github.io
nav:
  title: "Puentes del Turia en Valencia"
  url: /
  layout: about
  permalink: /about
  title: "Acerca de"
  url: /about
  title: "Soporte"
  url: /soporte
  
  
